-- Phase 1 — مرجع القرآن: السور الـ114 (بيانات ثابتة seeded في migration عشان تتطبّق على الريموت).
-- ملاحظة: مكتوب لكن لسه ماتطبّقش. الأسماء متنظّفة من التشكيل الثقيل ومن بادئة "سورة".

create type public.revelation_type as enum ('meccan', 'medinan');

create table public.surah (
  number smallint primary key check (number between 1 and 114),
  name_ar text not null,
  name_en text not null,
  ayah_count smallint not null check (ayah_count > 0),
  revelation public.revelation_type not null
);

alter table public.surah enable row level security;

-- مرجع عام: أي مستخدم مسجّل يقرا؛ التعديل للسوبر أدمن بس.
create policy surah_read on public.surah
  for select to authenticated using (true);
create policy surah_superadmin_write on public.surah
  for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

insert into public.surah (number, name_ar, name_en, ayah_count, revelation) values
  (1, 'الفاتحة', 'Al-Faatiha', 7, 'meccan'),
  (2, 'البقرة', 'Al-Baqara', 286, 'medinan'),
  (3, 'آل عمران', 'Aal-i-Imraan', 200, 'medinan'),
  (4, 'النساء', 'An-Nisaa', 176, 'medinan'),
  (5, 'المائدة', 'Al-Maaida', 120, 'medinan'),
  (6, 'الأنعام', 'Al-An''aam', 165, 'meccan'),
  (7, 'الأعراف', 'Al-A''raaf', 206, 'meccan'),
  (8, 'الأنفال', 'Al-Anfaal', 75, 'medinan'),
  (9, 'التوبة', 'At-Tawba', 129, 'medinan'),
  (10, 'يونس', 'Yunus', 109, 'meccan'),
  (11, 'هود', 'Hud', 123, 'meccan'),
  (12, 'يوسف', 'Yusuf', 111, 'meccan'),
  (13, 'الرعد', 'Ar-Ra''d', 43, 'medinan'),
  (14, 'إبراهيم', 'Ibrahim', 52, 'meccan'),
  (15, 'الحجر', 'Al-Hijr', 99, 'meccan'),
  (16, 'النحل', 'An-Nahl', 128, 'meccan'),
  (17, 'الإسراء', 'Al-Israa', 111, 'meccan'),
  (18, 'الكهف', 'Al-Kahf', 110, 'meccan'),
  (19, 'مريم', 'Maryam', 98, 'meccan'),
  (20, 'طه', 'Taa-Haa', 135, 'meccan'),
  (21, 'الأنبياء', 'Al-Anbiyaa', 112, 'meccan'),
  (22, 'الحج', 'Al-Hajj', 78, 'medinan'),
  (23, 'المؤمنون', 'Al-Muminoon', 118, 'meccan'),
  (24, 'النور', 'An-Noor', 64, 'medinan'),
  (25, 'الفرقان', 'Al-Furqaan', 77, 'meccan'),
  (26, 'الشعراء', 'Ash-Shu''araa', 227, 'meccan'),
  (27, 'النمل', 'An-Naml', 93, 'meccan'),
  (28, 'القصص', 'Al-Qasas', 88, 'meccan'),
  (29, 'العنكبوت', 'Al-Ankaboot', 69, 'meccan'),
  (30, 'الروم', 'Ar-Room', 60, 'meccan'),
  (31, 'لقمان', 'Luqman', 34, 'meccan'),
  (32, 'السجدة', 'As-Sajda', 30, 'meccan'),
  (33, 'الأحزاب', 'Al-Ahzaab', 73, 'medinan'),
  (34, 'سبإ', 'Saba', 54, 'meccan'),
  (35, 'فاطر', 'Faatir', 45, 'meccan'),
  (36, 'يس', 'Yaseen', 83, 'meccan'),
  (37, 'الصافات', 'As-Saaffaat', 182, 'meccan'),
  (38, 'ص', 'Saad', 88, 'meccan'),
  (39, 'الزمر', 'Az-Zumar', 75, 'meccan'),
  (40, 'غافر', 'Ghafir', 85, 'meccan'),
  (41, 'فصلت', 'Fussilat', 54, 'meccan'),
  (42, 'الشورى', 'Ash-Shura', 53, 'meccan'),
  (43, 'الزخرف', 'Az-Zukhruf', 89, 'meccan'),
  (44, 'الدخان', 'Ad-Dukhaan', 59, 'meccan'),
  (45, 'الجاثية', 'Al-Jaathiya', 37, 'meccan'),
  (46, 'الأحقاف', 'Al-Ahqaf', 35, 'meccan'),
  (47, 'محمد', 'Muhammad', 38, 'medinan'),
  (48, 'الفتح', 'Al-Fath', 29, 'medinan'),
  (49, 'الحجرات', 'Al-Hujuraat', 18, 'medinan'),
  (50, 'ق', 'Qaaf', 45, 'meccan'),
  (51, 'الذاريات', 'Adh-Dhaariyat', 60, 'meccan'),
  (52, 'الطور', 'At-Tur', 49, 'meccan'),
  (53, 'النجم', 'An-Najm', 62, 'meccan'),
  (54, 'القمر', 'Al-Qamar', 55, 'meccan'),
  (55, 'الرحمن', 'Ar-Rahmaan', 78, 'medinan'),
  (56, 'الواقعة', 'Al-Waaqia', 96, 'meccan'),
  (57, 'الحديد', 'Al-Hadid', 29, 'medinan'),
  (58, 'المجادلة', 'Al-Mujaadila', 22, 'medinan'),
  (59, 'الحشر', 'Al-Hashr', 24, 'medinan'),
  (60, 'الممتحنة', 'Al-Mumtahana', 13, 'medinan'),
  (61, 'الصف', 'As-Saff', 14, 'medinan'),
  (62, 'الجمعة', 'Al-Jumu''a', 11, 'medinan'),
  (63, 'المنافقون', 'Al-Munaafiqoon', 11, 'medinan'),
  (64, 'التغابن', 'At-Taghaabun', 18, 'medinan'),
  (65, 'الطلاق', 'At-Talaaq', 12, 'medinan'),
  (66, 'التحريم', 'At-Tahrim', 12, 'medinan'),
  (67, 'الملك', 'Al-Mulk', 30, 'meccan'),
  (68, 'القلم', 'Al-Qalam', 52, 'meccan'),
  (69, 'الحاقة', 'Al-Haaqqa', 52, 'meccan'),
  (70, 'المعارج', 'Al-Ma''aarij', 44, 'meccan'),
  (71, 'نوح', 'Nooh', 28, 'meccan'),
  (72, 'الجن', 'Al-Jinn', 28, 'meccan'),
  (73, 'المزمل', 'Al-Muzzammil', 20, 'meccan'),
  (74, 'المدثر', 'Al-Muddaththir', 56, 'meccan'),
  (75, 'القيامة', 'Al-Qiyaama', 40, 'meccan'),
  (76, 'الإنسان', 'Al-Insaan', 31, 'medinan'),
  (77, 'المرسلات', 'Al-Mursalaat', 50, 'meccan'),
  (78, 'النبإ', 'An-Naba', 40, 'meccan'),
  (79, 'النازعات', 'An-Naazi''aat', 46, 'meccan'),
  (80, 'عبس', 'Abasa', 42, 'meccan'),
  (81, 'التكوير', 'At-Takwir', 29, 'meccan'),
  (82, 'الانفطار', 'Al-Infitaar', 19, 'meccan'),
  (83, 'المطففين', 'Al-Mutaffifin', 36, 'meccan'),
  (84, 'الانشقاق', 'Al-Inshiqaaq', 25, 'meccan'),
  (85, 'البروج', 'Al-Burooj', 22, 'meccan'),
  (86, 'الطارق', 'At-Taariq', 17, 'meccan'),
  (87, 'الأعلى', 'Al-A''laa', 19, 'meccan'),
  (88, 'الغاشية', 'Al-Ghaashiya', 26, 'meccan'),
  (89, 'الفجر', 'Al-Fajr', 30, 'meccan'),
  (90, 'البلد', 'Al-Balad', 20, 'meccan'),
  (91, 'الشمس', 'Ash-Shams', 15, 'meccan'),
  (92, 'الليل', 'Al-Lail', 21, 'meccan'),
  (93, 'الضحى', 'Ad-Dhuhaa', 11, 'meccan'),
  (94, 'الشرح', 'Ash-Sharh', 8, 'meccan'),
  (95, 'التين', 'At-Tin', 8, 'meccan'),
  (96, 'العلق', 'Al-Alaq', 19, 'meccan'),
  (97, 'القدر', 'Al-Qadr', 5, 'meccan'),
  (98, 'البينة', 'Al-Bayyina', 8, 'medinan'),
  (99, 'الزلزلة', 'Az-Zalzala', 8, 'medinan'),
  (100, 'العاديات', 'Al-Aadiyaat', 11, 'meccan'),
  (101, 'القارعة', 'Al-Qaari''a', 11, 'meccan'),
  (102, 'التكاثر', 'At-Takaathur', 8, 'meccan'),
  (103, 'العصر', 'Al-Asr', 3, 'meccan'),
  (104, 'الهمزة', 'Al-Humaza', 9, 'meccan'),
  (105, 'الفيل', 'Al-Fil', 5, 'meccan'),
  (106, 'قريش', 'Quraish', 4, 'meccan'),
  (107, 'الماعون', 'Al-Maa''un', 7, 'meccan'),
  (108, 'الكوثر', 'Al-Kawthar', 3, 'meccan'),
  (109, 'الكافرون', 'Al-Kaafiroon', 6, 'meccan'),
  (110, 'النصر', 'An-Nasr', 3, 'medinan'),
  (111, 'المسد', 'Al-Masad', 5, 'meccan'),
  (112, 'الإخلاص', 'Al-Ikhlaas', 4, 'meccan'),
  (113, 'الفلق', 'Al-Falaq', 5, 'meccan'),
  (114, 'الناس', 'An-Naas', 6, 'meccan');